name: Main {{cookiecutter.service_name}} CI

on: [push, pull_request]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Pull repository
        uses: actions/checkout@v2.3.1

      - name: Setup .NET 5.0 SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Build
        run: cd src && dotnet build -c Release

      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: {{cookiecutter.service_name}}
          path: src/{{cookiecutter.service_name}}/bin/Release/{{cookiecutter.service_name}}.dll