name: Create template CI

on: [push, pull_request]

jobs:
  create_template:
    runs-on: ubuntu-latest

    steps:
      - name: Pull repository
        uses: actions/checkout@v2.3.1

      - name: Copy all to temp folder
        run: |
          cp -r * $RUNNER_TEMP
          rm -rf *

      - name: Checkout 'template'
        uses: actions/checkout@v2.3.1
        with:
          ref: template

      - name: Create template
        run: python $RUNNER_TEMP/create_template.py
      
      - name: Copy template to current directory
        run: cp -r $RUNNER_TEMP/template/* .

      - uses: EndBug/add-and-commit@v7.0.0
        with:
          branch: template
          author_name: github-actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com